### ISSUE TITLE
Classpath modification

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/JavaForVS#14]
Originally posted by @sriksrid at tunnelvisionlabs/LangSvcV2#45.

> Hi
> 
> I noticed that when I debug/run a file, a classpath is being specified (the jar file built), and this is causing my existing classpath to be ignored (I even added an extra cp command to the command line options, but that doesn't work either). Is there I way I can append entries to the classpath override for debug/run? I'm willing to edit the configuration files, if necessary. 
> 
> The build works fine if I specify the libraries in References; however they do not get carried over to debug - which is why I want to modify the classpath.
> 
> Thank you

**Comment by cas-mls** [comment]
This doesn't seem to be working in the latest release in the visual studio gallery.  I added a .jar file as a reference and it isn't being picked up in the debugger.  This eliminates a lot of the tools functionality which I was looking for.  Thank you.
