### ISSUE TITLE
Incorrect Output Window Behavior

### ISSUE THREAD

**Issue by BrainSlugs83** [tunnelvisionlabs/JavaForVS#26]
Hey guys -- cross logging this from [another repro'](https://github.com/Microsoft/vsminecraft/issues/14) at the maintainer's request.

Apologies, as the wording is Minecraft specific, and I haven't used your project directly, so I don't know the correct phraseology to use in all instances (so, I've re-posted it below, unaltered):

---

Instead of logging to the output window (like Eclipse or other IDEs do with other Minecraft mods -- or even like you would expect Visual Studio to do) instead of that, a new console window comes up and the output is displayed there.

Instead, that console stream should be redirected to the output window.  (Normal applications in Visual Studio log to the output window instead of creating new console windows -- Note: if you don't want to lose the other data that's being logged to the "Debug" source in the output window, you can create a new source for the output window).

First screenshot shows the Console Window being up on the display and the type of data that's both in the Console window and the "Debug" source of the output window.

![Console Window & Output Window](https://i.imgur.com/Ezw3Eqx.png)

Second screenshot shows an example of other sources for the Output window. -- Ideally, you could just create a "Minecraft" source and redirect stdout from "java.exe".

![Output Window Sources](https://i.imgur.com/78yt2vq.png)

When you implement this, please set the Output window's source to "Minecraft" by default when the debugger is attached.

**Comment by sharwell** [comment]
Hi @BrainSlugs83,

On the surface, I'm neither in favor of nor against this request. However, your statements about the way Visual Studio normally behaves are not correct. While the Output Window does show output from [`Debug.WriteLine`](https://msdn.microsoft.com/en-us/library/system.diagnostics.debug.writeline.aspx) (.NET applications) or [`OutputDebugString`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363362.aspx) (native applications), it does not send the result of stdout or stderr to the output window.

I'm marking _this_ request as **wontfix**, but I would be open the the following alternatives:
1. If Java has an equivalent to `Debug.WriteLine`, it would make sense to redirect output from that call to the Visual Studio output window.
2. If a third-party extension implements general support for redirecting stdout/stderr to the output window during a debugging session, I would be interested in discussing with the author of that extension ways in which it would work with the Java debugger in addition to the other debuggers already supported.

**Comment by BrainSlugs83** [comment]
Hmmm, that's sort of true -- the stdout redirection I'm thinking of is at build time -- so I made a mistake there - but I'm just thinking, in a typical Windows Application, a console is never opened -- so, why in a graphical Java application is a console window opened? -- is there a way to disable this?

The behavior is certainly not in line with what Eclipse does.  Eclipse shows all the Console Window stuff in it's own integrated window (for a graphical application). -- I'm just thinking that's analogous to using the Output window in Visual Studio. -- And the System.out.println is written to that integrated window.

Obviously for a console app, you would open a console window, but not for a graphical one, right?

**Comment by BrainSlugs83** [comment]
Regarding (1), all of the equivalent Java code I've seen to Debug.WriteLine uses System.out.println (for Windowed and graphical applications -- since a console is never opened, it only shows up in Eclipse).  So, I'm not sure that's possible.

Regarding (2), I'll keep it in mind, but the only software that I know of that does this is Eclipse (I'm guessing other Java IDE's do it as well, but I haven't used any in a long time).
