### ISSUE TITLE
Visual Studio community support has the wrong name

### ISSUE THREAD

**Issue by xiaoyongzhu** [tunnelvisionlabs/JavaForVS#27]
I have VS 2013 community installed in my machine but when installing the plugin it says "install on VS professional 2013".
I know essentially VS community == VS professional, but just report this issue in case we are not aware of this...

**Comment by sharwell** [comment]
Hi @zxzxy1988,

Thank you for taking the time to report this issue. I agree that the text is incorrect and could easily be confusing to users.

Unfortunately, extension authors do not have any control over that text, so I'm marking this as **invalid**. However, I recommend you send exactly what you wrote above (perhaps even a link to this issue) using the "Send a Frown" feature in Visual Studio. I know from experience that the Visual Studio team reads every single report sent through this feature, and many of my requests in the past have already been addressed.

![image](https://cloud.githubusercontent.com/assets/1408396/7558095/6adb9034-f762-11e4-9e1a-c1558448dde6.png)
